### ISSUE TITLE
The AUC of all anomaly classes is 0.5

### ISSUE THREAD

**Issue by sbjshxbxijs** [IMPLabUniPr/movad#1]
I trained the model (epochs=100) according to v2.4.yaml, then I loaded the weight file model-100.pt. The result is that  all calasses's AUC=0.5  I don't know the reason, why it is?

**Comment by hachreak** [comment]
Hi @sbjshxbxijs ,
thanks for using our code.
Are you using latest version of the code?
We experienced the same problem because we did a big code refactoring.
But, the we fixed the bug (see [patch](https://github.com/IMPLabUniPr/movad/commit/72ef9aeb428e2f1fabd24f30abe5b5410e749c05)).
In the following days, we will also release the pretrained.

**Comment by hachreak** [comment]
The bug was fixed (and [pretrained](https://github.com/IMPLabUniPr/movad/releases/tag/v1.0) are now available).
