### ISSUE TITLE
Incompatibility of Torchvision module , from torchvision.transform.functional.

### ISSUE THREAD

**Issue by ByteWiizard** [IMPLabUniPr/movad#2]
error i am facing is:

dota_conda) -bash-4.2$ python src/main.py --config cfgs/v4_2.yml --output output/v4_2/ --phase train --epochs 1000 --epoch -1 Traceback (most recent call last): File "src/main.py", line 11, in <module> from dota import setup_dota, Dota File "/home/Yaman/mee/movad-main/src/dota.py", line 12, in <module> from pytorchvideo import transforms as T File "/home/Yaman/yes/envs/dota_conda/lib/python3.8/site-packages/pytorchvideo/transforms/_init_.py", line 3, in <module> from .augmix import AugMix # noqa File "/home/Yaman/yes/envs/dota_conda/lib/python3.8/site-packages/pytorchvideo/transforms/augmix.py", line 6, in <module> from pytorchvideo.transforms.augmentations import ( File "/home/Yaman/yes/envs/dota_conda/lib/python3.8/site-packages/pytorchvideo/transforms/augmentations.py", line 10, in <module> from torchvision.transforms.functional import InterpolationMode ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms.functional' (/home/Yaman/yes/envs/dota_conda/lib/python3.8/site-packages/torchvision/transforms/functional.py)

If anyone could help

**Comment by hachreak** [comment]
Hi @ByteWiizard 
sorry for the long delay for the reply.
As mentioned [here](https://github.com/facebookresearch/SlowFast/issues/441#issuecomment-1008674575), I think you have this error because the library pytorchvideo requires at least torchvision>=0.9.0
If you look inside [the code](https://github.com/pytorch/vision/blob/v0.9.0/torchvision/transforms/functional.py#L22), this file contains the class `InterpolationMode` mentioned from the error.
